import { pxToRem } from 'utils/stylingUtils';
import createBasicTheme from './createBasicTheme';
import { colors, gradients, shadows } from '../constants';

const mainTheme = createBasicTheme({
  customShadows: shadows,
  palette: {
    primary: {
      main: colors.primaryDefault,
      dark: colors.primaryDark,
      light: colors.primaryLight,
      light2: colors.primaryLight2,
      contrastText: colors.primaryMostLighter,
    },
    secondary: {
      main: colors.secondaryDefault,
      dark: colors.secondaryDark,
      light: colors.secondaryLight,
      light2: colors.secondaryLight2,
    },
    error: {
      main: colors.errorDefault,
      dark: colors.errorDark,
      light: colors.errorLight,
      light2: colors.errorLight2,
    },
    warning: {
      main: colors.warningDefault,
      dark: colors.warningDark,
      light: colors.warningLight,
      light2: colors.warningLight2,
    },
    success: {
      main: colors.successDefault,
      dark: colors.successDark,
      light: colors.successLight,
      light2: colors.successLight2,
    },
    info: {
      main: colors.infoDefault,
      dark: colors.infoDark,
      light: colors.infoLight,
      light2: colors.infoLight2,
    },
    background: {
      default: colors.backgroundPrimary,
    },
    grey: {
      700: colors.grey700,
      600: colors.grey600,
      500: colors.grey500,
      400: colors.grey400,
      300: colors.grey300,
      200: colors.grey200,
      100: colors.grey100,
      50: colors.grey50,
    },
    gradients,
  },
  typography: {
    h1: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(38),
      lineHeight: '135%',
      letterSpacing: '-0.04em',
    },
    h2: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(32),
      lineHeight: '138%',
      letterSpacing: '-0.03em',
    },
    h3: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(26),
      lineHeight: '138%',
      letterSpacing: '-0.02em',
    },
    h4: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(22),
      lineHeight: '140%',
      letterSpacing: '-0.02em',
    },
    h5: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(20),
      lineHeight: '148%',
      letterSpacing: '-0.02em',
    },
    h6: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(18),
      lineHeight: '148%',
      letterSpacing: '-0.02em',
    },
    bodyDefaultBook: {
      fontFamily: 'MalloryMPBook',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(14),
      lineHeight: '170%',
      letterSpacing: '-0.02em',
    },
    bodyDefaultMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(14),
      lineHeight: '170%',
    },
    bodySmallBook: {
      fontFamily: 'MalloryMPBook',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(12),
      lineHeight: '170%',
    },
    bodySmallMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(12),
      lineHeight: '170%',
    },
    subtitleBook: {
      fontFamily: 'MalloryMPBook',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(15),
      lineHeight: '148%',
    },
    subtitleMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(15),
      lineHeight: '148%',
    },
    captionMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(11),
      lineHeight: '100%',
    },
    overlineDefaultMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(12),
      lineHeight: '133%',
    },
    overlineSmallMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(11),
      lineHeight: '133%',
    },
    buttonSmall: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(13),
      lineHeight: '150%',
    },
    buttonMedium: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(14),
      lineHeight: '150%',
    },
    buttonLarge: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: pxToRem(15),
      lineHeight: '150%',
    },
    bodyDefaultMediumUnderline: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(14),
      lineHeight: '170%',
      textDecoration: 'underline',
    },
    bodySmallMediumUnderline: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(12),
      lineHeight: '170%',
      textDecoration: 'underline',
    },
    button: {
      textTransform: 'none',
    },
    logoUnderline: {
      fontFamily: 'MalloryMPMedium',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: pxToRem(20),
      lineHeight: '148%',
      letterSpacing: '-0.02em',
      textDecoration: 'underline',
    },
  },
});

export default mainTheme;
