export default {
  common: {
    logo: 'HIT ME UP',
    welcomePage: 'Welcome Page',
    welcomePageTitle: 'Best Learning app to improve your vocabulary',
    welcomePageSubtitle: 'Choose and learn.',
    signUp: 'Sign up',
    login: 'Log in',
    settingsPageTitle: 'Settings',
    settingsPagePersonalInfoItem: 'Personal Info',
    settingsPagePersonalPlanItem: 'Personal Plan',
    continue: 'Continue',
    wordAddButtonTitle: 'Add',
    wordDelButtonTitle: 'Del',
    wordAddLinkTitle: 'Add new words for learning',
    wordListEmptyTitle: 'Oops!',
    wordListEmptySubTitle: 'Your Words will leave here',
    wordListErrorSubtitle: 'Something’s wrong',
    wordListErrorLabelFirst: 'Your words can’t be loaded right now.',
    wordListErrorLabelSecond: 'Please try again later.',
  },
};
